# Generated by Django 4.2.30 on 2026-06-03 12:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorNode',
            fields=[
                ('node_id', models.AutoField(primary_key=True, serialize=False)),
                ('node_identifier', models.CharField(help_text='e.g. NODE_001', max_length=50, unique=True)),
                ('location_label', models.CharField(help_text='e.g. Gulu Main Store - Section A', max_length=200)),
                ('gateway_id', models.CharField(blank=True, help_text='SIM card number or GSM gateway ID', max_length=100, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance')], default='active', max_length=20)),
                ('last_reading_at', models.DateTimeField(blank=True, null=True)),
                ('pending_command', models.CharField(choices=[('ON', 'Turn On'), ('OFF', 'Turn Off'), ('NONE', 'No Command')], default='NONE', max_length=10)),
                ('installed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'sensor_nodes',
                'ordering': ['location_label'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('role', models.CharField(choices=[('farmer', 'Farmer'), ('store_manager', 'Store Manager'), ('admin', 'System Admin')], default='farmer', max_length=20)),
                ('password_hash', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'users',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Threshold',
            fields=[
                ('threshold_id', models.AutoField(primary_key=True, serialize=False)),
                ('min_temp', models.FloatField(default=10.0, help_text='Minimum temperature (°C) — alert below this')),
                ('max_temp', models.FloatField(default=35.0, help_text='Maximum temperature (°C) — alert above this')),
                ('min_humidity', models.FloatField(default=40.0, help_text='Minimum humidity (%) — alert below this')),
                ('max_humidity', models.FloatField(default=75.0, help_text='Maximum humidity (%) — alert above this')),
                ('risk_duration', models.IntegerField(default=6, help_text='Hours of sustained risk before escalation')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('node', models.OneToOneField(db_column='node_id', on_delete=django.db.models.deletion.CASCADE, related_name='threshold', to='monitoring.sensornode')),
            ],
            options={
                'db_table': 'thresholds',
            },
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('reading_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('temperature_c', models.FloatField(help_text='Temperature in °C from DHT22')),
                ('humidity_pct', models.FloatField(help_text='Relative humidity % from DHT22')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Server receipt timestamp')),
                ('device_ts', models.DateTimeField(blank=True, help_text='Timestamp from device (if provided)', null=True)),
                ('node', models.ForeignKey(db_column='node_id', on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='monitoring.sensornode')),
            ],
            options={
                'db_table': 'readings',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertLog',
            fields=[
                ('alert_id', models.AutoField(primary_key=True, serialize=False)),
                ('ari_value', models.FloatField(help_text='Computed ARI score 0–100')),
                ('risk_level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10)),
                ('message', models.TextField(help_text='Alert message body')),
                ('sent_to', models.CharField(help_text='Phone number or email alert was sent to', max_length=255)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('action_taken', models.BooleanField(default=False, help_text='Has the farmer acknowledged/acted?')),
                ('sms_sid', models.CharField(blank=True, help_text='Twilio message SID for delivery tracking', max_length=100)),
                ('node', models.ForeignKey(db_column='node_id', on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='monitoring.sensornode')),
                ('reading', models.OneToOneField(blank=True, db_column='reading_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert', to='monitoring.reading')),
            ],
            options={
                'db_table': 'alert_logs',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddIndex(
            model_name='reading',
            index=models.Index(fields=['node', '-recorded_at'], name='readings_node_id_2adab9_idx'),
        ),
        migrations.AddIndex(
            model_name='alertlog',
            index=models.Index(fields=['node', '-sent_at'], name='alert_logs_node_id_c32770_idx'),
        ),
        migrations.AddIndex(
            model_name='alertlog',
            index=models.Index(fields=['risk_level'], name='alert_logs_risk_le_2d0596_idx'),
        ),
    ]
