# Generated by Django 4.2.30 on 2026-06-09 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertlog',
            name='alert_type',
            field=models.CharField(choices=[('ari_risk', 'ARI Risk'), ('threshold_breach', 'Threshold Breach'), ('node_offline', 'Node Offline')], default='ari_risk', max_length=20),
        ),
        migrations.AlterField(
            model_name='alertlog',
            name='ari_value',
            field=models.FloatField(blank=True, help_text='Computed ARI score 0–100', null=True),
        ),
    ]
