# Generated by Django 4.2.30 on 2026-06-10 (hand-edited to handle existing rows)

import secrets
from django.db import migrations, models


def populate_api_keys(apps, schema_editor):
    """Generate a unique 64-char hex api_key for every existing SensorNode row."""
    SensorNode = apps.get_model('monitoring', 'SensorNode')
    for node in SensorNode.objects.filter(api_key=''):
        node.api_key = secrets.token_hex(32)
        node.save(update_fields=['api_key'])


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_user_push_token'),
    ]

    operations = [
        # 1. Add moisture_pct (nullable — no constraint issues)
        migrations.AddField(
            model_name='reading',
            name='moisture_pct',
            field=models.FloatField(
                blank=True, null=True,
                help_text='Grain/soil moisture % from capacitive sensor (ESP32 ADC pin 34)'
            ),
        ),
        # 2. Add api_key WITHOUT unique=True first so existing rows get ''
        migrations.AddField(
            model_name='sensornode',
            name='api_key',
            field=models.CharField(
                blank=True, max_length=64, default='',
                help_text='Auto-generated per-node secret key (do not share publicly)'
            ),
        ),
        # 3. Populate unique keys for all existing rows
        migrations.RunPython(populate_api_keys, migrations.RunPython.noop),
        # 4. Now safe to add the UNIQUE constraint
        migrations.AlterField(
            model_name='sensornode',
            name='api_key',
            field=models.CharField(
                blank=True, max_length=64, unique=True,
                help_text='Auto-generated per-node secret key (do not share publicly)'
            ),
        ),
        # 5. Add mac_address
        migrations.AddField(
            model_name='sensornode',
            name='mac_address',
            field=models.CharField(
                blank=True, null=True, max_length=17,
                help_text='Node Wi-Fi/Ethernet MAC address (AA:BB:CC:DD:EE:FF)'
            ),
        ),
        migrations.AlterField(
            model_name='sensornode',
            name='gateway_id',
            field=models.CharField(
                blank=True, null=True, max_length=100,
                help_text='Legacy field — use mac_address for new Wi-Fi nodes'
            ),
        ),
        migrations.AlterField(
            model_name='sensornode',
            name='location_label',
            field=models.CharField(
                max_length=200,
                help_text='Physical location, e.g. Gulu Main Store — Section A'
            ),
        ),
        migrations.AlterField(
            model_name='sensornode',
            name='node_identifier',
            field=models.CharField(
                max_length=50, unique=True,
                help_text='Human-readable node ID, e.g. NODE_001'
            ),
        ),
    ]
