# Generated by Django 4.2.30 on 2026-06-28 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_sensornode_owner_backfill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensornode',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='The user (Farmer/Store Manager/Admin) who registered this node.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_nodes', to='monitoring.user'),
        ),
    ]
